### ISSUE TITLE
Create 1.8 branch

### ISSUE THREAD

**Issue by juho-jaakkola** [teamwebgalli/galliElggEmbed#2]
Create a separate `1.8` branch from the current master, so master branch can start accepting updates targeted for Elgg 1.9 and higher.

**Comment by teamwebgalli** [comment]
Created a new branch @juho-jaakkola. Could you resend the pull requests against the master once more?
not familiar with the git interfaces. Sorry for the troubles caused.

**Comment by teamwebgalli** [comment]
Here is the 1.8 branch https://github.com/teamwebgalli/galliElggEmbed/tree/1.8
