### ISSUE TITLE
Submit the plugin to Packagist

### ISSUE THREAD

**Issue by juho-jaakkola** [teamwebgalli/galliElggEmbed#6]
Now that the plugin has a `composer.json` file, please submit it to Packagist (https://packagist.org/packages/submit) so it can be installed via Composer without explicitly defining a VCS repository URL in the project that's using it.

**Comment by teamwebgalli** [comment]
Done. Thank you..

**Comment by juho-jaakkola** [comment]
Are you sure the submitting was successful? I cannot find any search results in Packagist either with "teamwebgalli" or "galliElggEmbed".

**Comment by juho-jaakkola** [comment]
I'm still unable to find the package from Packagist.
